version: '3'

services:
  db:
    container_name: odm2admindb
    image: kartoza/postgis
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: odm2
      POSTGRES_PORT: 5432
    expose:
      - "5432"
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
  app:
    container_name: odm2adminapp
    restart: always
    build: 
      context: ../../
      dockerfile: ./docker/odm2admin/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../../docker/docker-deploy/settings:/CZ-Manager/templatesAndSettings/settings
      - ../../:/CZ-Manager

  redis:
    container_name: odm2adminredis
    restart: always
    image: redis:latest
    expose:
      - "6379"

volumes:
  postgres-data:
  CZ-Manager: